#! /bin/bash

# Wait until libvirtd/kvm runtime starts
until virsh list >/dev/null 2>&1; do
    sleep 1
done

# Start pfsense
virsh start pfsense

# Wait until pfsense is up and running, note that the IP address should match your router's IP address
until ping -c1 192.168.4.1 >/dev/null 2>&1; do
    sleep 1
done

# Start pihole
virsh start pihole

# `sudo cp` this file to /usr/bin/
# chmod this file to 755
